package com.agendaqr.destinations.presentation

/**
 * T12 — copy centralizado de la app (UI en español).
 *
 * El texto es copy CONGELADO de la spec UX (docs/04-ux): este objeto
 * no cambia una sola palabra, solo la centraliza para mantener una
 * única fuente de copy y preparar i18n sin tocar las pantallas.
 * Las plantillas con interpolación ($…) permanecen en sus call-sites
 * porque su valor es dinámico.
 *
 * DECISIÓN (D2): se evaluó migrar a composeResources/values/strings.xml
 * para i18n automático; se queda el objeto centralizado porque (1) el
 * módulo presentation aún no expone el accessor `Res` a las features que
 * comparten los literales (iosMain incluido), (2) strings.xml exige
 * regenerar el accessors por módulo y trasladar también los androidMain/
 * iosMain actuales, y (3) el copy está congelado (no hay i18n en V1).
 * La migración queda registrada como paso previo obligatorio cuando V2
 * necesite idiomas.
 */
internal object AppStrings {
    val AbriendoComprobante = "Abriendo comprobante…"
    val ActividadReciente = "Actividad reciente"
    val ActividadesRecientes = "Actividades recientes"
    val attachReceiptNow = "Adjuntar comprobante ahora"
    val AgendaQr = "Agenda QR"
    // V1.1 (ADR-0005, S01): sección de entradas recientes y tile vivo.
    val Recientes = "Recientes"
    val UltimoQrOActividad = "Último QR o actividad reciente"
    val emptyDestinationsHint = "Agrega tu primer QR para empezar."
    val Analizando = "Analizando…"
    val associateToExistingOperation = "Asociar a actividad existente"
    val Anadir = "Añadir"
    val searchIntroHint = "Busca QR, actividades, contextos o comprobantes."
    val BuscandoEnAgendaQr = "Buscando en Agenda QR…"
    val Buscar = "Buscar"
    val searchPlaceholder = "Buscar QR, actividades, comprobantes o contextos"
    val BuscarEnAgendaQr = "Buscar en Agenda QR"
    val BuscarOperaciones = "Buscar actividades"
    val changeOperationWithReceipts = "Cambiar actividad con comprobantes"
    val Cancelar = "Cancelar"
    val CargandoContextos = "Cargando contextos…"
    val CargandoContexto = "Cargando contexto…"
    val CargandoDestinosQr = "Cargando QR…"
    val Categoria = "Categoría"
    val Cerrar = "Cerrar"
    val CerrarSesion = "Cerrar sesión"
    val Cobro = "Cobro"
    val shareFromAnotherAppHint = "Comparte una imagen o PDF desde otra app con Agenda QR. La importación continuará aquí para revisar lo que se encontró."
    val Compartir = "Compartir"
    val Comprobante = "Comprobante"
    val receiptReceivedTitle = "Comprobante recibido"
    val Comprobante2 = "Comprobante · "
    val ComprobantesSinAsociar = "Comprobantes sin asociar"
    val ComprobantesSinAsociar2 = "Comprobantes sin asociar: "
    val Comprobantes = "Comprobantes"
    val ConceptoOpcional = "Concepto (opcional)"
    val Concepto = "Concepto: "
    val Contextos = "Contextos"
    val Contrasena = "Contraseña"
    val Correo = "Correo"
    val CrearCuenta = "Crear cuenta"
    val createOperationFromThis = "Crear nueva actividad con esto"
    val Camara = "Cámara"
    val Desasociar = "Desasociar"
    val Descartar = "Descartar"
    // Fase 4: copy que el DS exige al llamador (core/ui no hardcodea copy).
    val Mas = "Más"
    val CargarMas = "Cargar más"
    val NoHayMasElementos = "No hay más elementos"
    val Cargando = "Cargando…"
    val DesdeOtraApp = "Desde otra app"
    val shareFromAnotherAppLabel = "Desde otra app: comparte una imagen o PDF con Agenda QR."
    val DestinoNoEncontrado = "QR no encontrado"
    val Inicio = "Inicio"
    val Detalle = "Detalle"
    val EditaElDestinoParaImportar = "Edita el QR para importar un código válido."
    val Editar = "Editar"
    val EditarQr = "Editar QR"
    val ElementoExistente = "Elemento existente"
    val ElementosQueNecesitanRevision = "Elementos que necesitan revisión"
    val Eliminar = "Eliminar"
    val EliminarComprobante = "Eliminar comprobante"
    val EliminarDestino = "Eliminar QR"
    val EliminarOperacion = "Eliminar actividad"
    val EncuadreElCodigoQr = "Encuadra el código QR" // ADR-0008: tuteo (antes "Encuadre")
    val irreversibleActionWarning = "Esta acción no se puede deshacer."
    val sensitiveChangeWarning = "Esta actividad tiene comprobantes. El comprobante no será modificado."
    val analyzingReceipt = "Estamos analizando el comprobante."
    val FaltaElCodigoQrUsa = "Falta el código QR: usa Cámara o Galería"
    val Fecha = "Fecha"
    val Galeria = "Galería"
    val GaleriaVarios = "Galería (varios)"
    val batchSavedKeepReviewNotice = "Guardado. Los elementos pendientes conservan su revisión."
    val savingRecognizedItems = "Guardando elementos reconocidos…"
    val Guardar = "Guardar"
    val GuardarCambio = "Guardar cambio"
    val GuardarCambios = "Guardar cambios"
    val GuardarDeTodosModos = "Guardar de todos modos"
    val GuardarReconocidos = "Guardar reconocidos"
    val ImportaUnQrConCamara = "Importa un QR con Cámara o Galería para previsualizarlo aquí"
    val Importando = "Importando…"
    val IniciaSesionParaAccederA = "Inicia sesión para acceder a tu agenda."
    val IniciarSesion = "Iniciar sesión"
    val operationKeptOnReceiptDelete = "La actividad asociada se conservará."
    val LasOperacionesCandidatasYaNo = "Las actividades candidatas ya no están disponibles."
    val Limpiar = "Limpiar"
    val LosContextosAgrupanTusQr = "Los contextos agrupan tus QR y actividades."
    val MonedaOpcional = "Moneda (opcional)"
    val Moneda = "Moneda: "
    val MontoOpcional = "Monto (opcional)"
    val MostrarQr = "Mostrar QR"
    val noAutomaticMatch = "No encontramos una coincidencia automática. Puedes elegir manualmente una actividad."
    val NoHayQrParaRevisar = "No hay QR para revisar"
    val noUnassociatedReceipts = "No hay comprobantes sin asociar"
    val noOperationsAvailable = "No hay actividades disponibles."
    val NoPudimosMostrarElElemento = "No pudimos mostrar el elemento existente."
    val NoSePudoAbrirEl = "No se pudo abrir el comprobante"
    val Nombre = "Nombre"
    val Nota = "Nota"
    val NotaOpcional = "Nota (opcional)"
    val Nota2 = "Nota: "
    val Nuevo = "Nuevo"
    val Operaciones = "Actividades"
    val OperacionNoEncontrada = "Actividad no encontrada"
    val Origen = "Origen: "
    val Pago = "Pago"
    val PersonaOEntidadOpcional = "Persona o entidad (opcional)"
    val PersonaOEntidad = "Persona o entidad: "
    val PodrasAdjuntarComprobantesMasAdelante = "Podrás adjuntar comprobantes más adelante"
    val PruebaConOtraPalabraO = "Prueba con otra palabra o revisa la ortografía."
    val PudoHaberSidoEliminada = "Pudo haber sido eliminada."
    val PudoHaberSidoEliminadoEn = "Pudo haber sido eliminado en otro dispositivo."
    val Qr = "QR"
    val QrSinContenido = "QR sin contenido"
    val Qr2 = "QR · "
    val Reintentar = "REINTENTAR"
    val Registrar = "Registrar"
    val ReintentarAhora = "Reintentar ahora"
    val ReintentarClasificacion = "Reintentar clasificación"
    val ResultadoDeImportacion = "Resultado de importación"
    val RevisarQr = "Revisar QR"
    val SeleccionarContexto = "Seleccionar contexto"
    val SinComprobanteAdjunto = "Sin comprobante adjunto"
    val SinConexionLosCambiosSe = "Sin conexión — los cambios se guardan localmente y se sincronizarán al recuperar conectividad."
    val SinContextos = "Sin contextos"
    val SinContextosDisponibles = "Sin contextos disponibles."
    val SinDestinos = "Sin QR"
    val SinResultados = "Sin resultados"
    val TraeAAgendaQrAlgo = "Trae a Agenda QR algo que ya tienes."
    val TraeVariosElementosAAgenda = "Trae varios elementos a Agenda QR."
    val VerBandejaDeRespaldos = "Ver bandeja de respaldos"
    val VerExistente = "Ver existente"
    val Volver = "Volver"
    val VolverALaLista = "Volver a la lista"
    val VolverAResultado = "Volver a resultado"
    val VuelveEImportaDesdeCamara = "Vuelve e importa desde Cámara o Galería."
    val DestinationRouteTurnstile = "destination_route_turnstile"
    // Fase 3: transición entre superficies (AppRoute) del stack raíz.
    val SurfaceRouteTurnstile = "surface_route_turnstile"
    val QrSinNombre = "QR sin nombre"
    val SinNombre = "Sin nombre"
    val VerMas = "Ver más"
    val Reconocidos = "Reconocidos"
    val PosiblesDuplicados = "Posibles duplicados"
    val PendientesDeRevision = "Pendientes de revisión"
    val CrearContexto = "Crear contexto"
    val Crear = "Crear"
    val QuitarContexto = "Quitar contexto"
    val ElNombreEsObligatorio = "El nombre es obligatorio"
    val TuInformacionEstaGuardadaEnElDispositivo = "Tu información está guardada en el dispositivo."
    val ComprobanteDuplicado = "Comprobante duplicado"
    val duplicateReceiptWarningPrefix = "Parece que este comprobante ya está guardado.\nArchivo: "
    val incomingReceiptExplanationPrefix = "Se guardará en tu bandeja de respaldos sin asociar.\nArchivo: "
    val Guardando = "Guardando…"
    // Fase 2 (auditoría a11y): validación de auth + estado ocupado.
    val IngresaUnCorreoValido = "Ingresa un correo válido"
    // Fase 4: literales que esquivaban la regla D2 dentro de expresiones.
    val FormatoFecha = "Usa el formato dd/mm/aaaa"
    // Ronda 2 (Área B): permiso de cámara y lectura de QR.
    val AbrirAjustes = "Abrir ajustes"
    val PermisoCamaraContexto = "Usamos la cámara solo para escanear códigos QR."
    val CodigoQrDetectado = "Código QR detectado"
    // Ronda 2 (Área F): anuncios accesibles de estado (por evento).
    val SincronizacionCompletada = "Sincronización completada"
    val Eliminado = "Eliminado"
    val GuardadoOk = "Guardado"
    val Minimo6Caracteres = "Mínimo 6 caracteres"
    val IniciandoSesion = "Iniciando sesión…"
    val AsociarAhora = "Asociar ahora"
    val AunNoHayOperaciones = "Aún no hay actividades"
    val NoHayCoincidencias = "No hay coincidencias"
    val registerFirstPaymentHint = "Registra tu primer pago o cobro."
    val tryAnotherSearchHint = "Prueba con otra búsqueda."
    val RegistrarOperacion = "Registrar actividad"
    val LimpiarBusqueda = "Limpiar búsqueda"
    val singleMatchTitle = "Parece corresponder a"
    val noMatchTitle = "No encontramos coincidencia"
    val QrImportado = "QR importado"
    val ComprobanteNoEncontrado = "Comprobante no encontrado"
    val Favoritos = "Favoritos"
    /** S01 (tile Favoritos): estado del filtro expresado con TEXTO visible
     * (§11) — el acento del tile ya no cambia para no reutilizar un acento
     * de contexto con otro significado (contrato §5.1). */
    val FavoritosActivado = "Favoritos: activado"
    val Favorito = "Favorito"
    val MarcarFavorito = "Marcar favorito"
    val SeccionComprobantes = "Comprobantes"
    val checkMark = "✓ "
    val dupMark = "! "
    val pendingMark = "? "
    val ComprobanteAdjuntoVistaPreviaPendienteEnIos = "Comprobante adjunto (vista previa pendiente en iOS)"
    val PdfAdjuntoSinVistaPrevia = "PDF adjunto (sin vista previa)"
    val VistaPreviaNoDisponible = "Vista previa no disponible"
    val Contenido = "Contenido"
    val EditarOperacion = "Editar actividad"
    val AunNoHayDestinos = "Aún no hay QR"
    val NoSeEncontraronDestinos = "No se encontraron QR"
    val PruebaConOtraBusquedaOLimpia = "Prueba con otra búsqueda o limpia los filtros."
    val ParaContextoElegido = "Para: "
    val ParaElegirContexto = "Para: elegir contexto (opcional)"
    val ContextoGenerico = "Contexto"
}
